# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# This is the top-level workflow to run on all pull-requests, and invokes
# several other workflow dependencies
name: Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  pre_run:
    name: Call Pre Run Check
    steps:
      - uses: ./.github/workflows/pre-run-check.yml
  verilator:
    name: Call Verilator
    needs: pre_run
    steps:
      - uses: ./.github/workflows/build-test-verilator.yml
  interactive_dbg:
    name: Call Interactive Debug
    needs: pre_run
    steps:
      - uses: ./.github/workflows/interactive-debugging.yml
  doc_gen:
    name: Call Doc Gen
    needs: pre_run
    steps:
      - uses: ./.github/workflows/doc-gen.yml
  post_run:
    name: Call Post Run Final
    needs: [verilator interactive_dbg doc_gen]
    steps:
      - run: echo "Finalize"
